# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
# While our "example" application has the platform-specific code,
# for simplicity we are compiling and testing everything on the Ubuntu environment only.
# For multi-OS testing see the `cross.yml` workflow.

on: [push, pull_request]

name: noir_rs

jobs:
  fmt:
    name: Fmt check
    runs-on: ubuntu-latest
    container:
      image: docker.io/rust:latest
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
            submodules: 'true'

      - name: Test
        run: cargo fmt --check

  test:
    name: Build&Test
    runs-on: ubuntu-latest
    container:
      image: docker.io/rust:latest
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
            submodules: 'true'
      
      - name: Install | Clang
        run: apt update && apt install -y libclang-dev

      - name: Install | CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.24.0'

      - name: Build
        run: cargo build -vv --features barretenberg
        
      - name: Test
        run: cargo test -vv --features barretenberg

      - name: Package barretenberg artifact (linux-x86_64)
        working-directory: target/debug
        run: |
          tar -czvf build-linux-x86_64.tar.gz build

      - name: Upload artifact (linux-x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-x86_64
          path: build-linux-x86_64.tar.gz
          retention-days: 3
